# coding: utf-8 

import os
import argparse

# working folder / dossier de travail
folderMain = os.getcwd() 

# lexicons folder / dossier lexiques
folderLexicon = os.path.join(folderMain,"lexicons") 
  # contains files for each langue's lexicon, usage : module1
  # contient les fichiers lexiques de chaque langue, utilisation : module1

# phonemes folder / dossier phonèmes
folderPhonemes = os.path.join(folderMain,"phonemes")
  # this folder is generated by module1 if necessary
    # contains the list of phonems for each langue
  # ce dossier est généré par module1 si necessaire
    # contient la liste des phonèmes de chaque langue

# svg folder / dossier svg
folderSVG = os.path.join(folderMain,"svg")
  # contains SVG subfolders
  # contient les sous-dossiers SVG

# SVG subfolder Templates / sous dossier SVG Patrons
folderTemplate = os.path.join(folderSVG,"svg_template")

# SVG subfolder Intermediary SVG / sous-dossier SVG Intermédaires
folderInter = os.path.join(folderSVG,"svg_inter")

# SVG subfolder Final SVG / sous-dossier SVG Finaux
folderFinaux = os.path.join(folderSVG,"svg_finaux")

# SVG subfolder Clean SVG / sous-dossier SVG "propres"
folderClean = os.path.join(folderSVG,"svg_clean")
  # specific folder, usage: svg's XML parsing
  # dossier specifique, utilité: parsing du XML formant le svg

# web interface folder / dossier interface web
folderInterface = os.path.join(folderMain,"interface")
